-- Bundled Universal Auto-Trade. Generated by tools/bundle.py. Do not edit.
-- Source of truth: src/*.lua  (regenerate: python tools/bundle.py)
local __M = {}
__M["lib.parse"] = (function()
local M = {}

-- Returns the first gem amount found in `s` as an integer, or nil.
-- Understands k/m suffixes (case-insensitive) and comma grouping.
function M.gems(s)
  if type(s) ~= "string" then return nil end
  s = s:lower()
  -- number with optional k/m suffix: e.g. 1.1m, 900k, 7k
  local num, suffix = s:match("([%d][%d,%.]*)%s*([km])")
  if num then
    local n = tonumber((num:gsub(",", "")))
    if not n then return nil end
    if suffix == "k" then n = n * 1000 elseif suffix == "m" then n = n * 1000000 end
    return math.floor(n + 0.5)
  end
  -- plain number, possibly comma-grouped
  local plain = s:match("[%d][%d,]*%.?%d*")
  if plain then
    local n = tonumber((plain:gsub(",", "")))
    if n then return math.floor(n + 0.5) end
  end
  return nil
end

return M

end)()
__M["lib.feed"] = (function()
local M = {}

-- Normalize a raw feed table { [name] = {value=?, demand=?} }.
-- Drops entries that aren't tables. Marks nil-value entries as naValue=true.
function M.normalize(raw)
  local out = {}
  if type(raw) ~= "table" then return out end
  for name, entry in pairs(raw) do
    if type(name) == "string" and type(entry) == "table" then
      local value = tonumber(entry.value)
      out[name] = {
        value = value,                 -- may be nil
        demand = tonumber(entry.demand) or 0,
        naValue = value == nil,
      }
    end
  end
  return out
end

function M.count(norm)
  local n = 0
  for _ in pairs(norm) do n = n + 1 end
  return n
end

return M

end)()
__M["lib.config"] = (function()
local M = {}

function M.defaults()
  return {
    enabled = false,
    testMode = true,          -- do everything but never press confirm (safe)
    activeVendItem = "",      -- the ONE item the bot sells (blank = highest-value For Sale)
    minSellPct = 90,          -- hard floor: never confirm a sale below value * this%
    globalMarkupPct = 5,      -- ask = value * (1 + markup/100)
    bandPct = 10,             -- ceiling/floor = value * (1 +/- band/100)
    demandScaling = true,     -- high demand -> more markup, less concession
    tradeUnitMode = "single_type_qty", -- single_copy | single_type_qty | multi_basket
    tradeTimeoutSec = 60,
    negotiation = { maxRounds = 4, concedeStepPct = 3, chatCooldownSec = 4 },
    ads = { rotatingAds = false, autoInvite = false, stockOnly = true, intervalSec = 45 },
    items = {},               -- [name] = { value?, markupPct?, bandPct?, forSale? }

    -- Auto-buyer at gem cap (OFF by default; sell mode is the primary use)
    buyEnabled = false,
    gemCap = 100000000,       -- switch to buy-only at/above this many gems
    gemCapBuffer = 5000000,   -- resume selling once gems fall below (cap - buffer)
    buyDiscountPct = 10,      -- maxBuy = value * (1 - buyDiscount/100)
    buy = {},                 -- [name] = { wantBuy?, maxBuyPrice?, maxQty? }

    -- Scam-guard + per-player throttling
    cooldownSec = 30,         -- min seconds between trades with the same player
    blocklist = {},           -- [playerName] = true

    -- 24/7 survival
    survival = { autoReconnect = true, antiAfk = true, watchdog = true,
                 watchdogMaxErrors = 5 },

    -- Discord webhook (url stored locally only; blank = disabled)
    webhook = { url = "", onSale = true, onCap = true, onDisconnect = true, onError = true },

    -- Housekeeping
    feedRefreshSec = 1800,    -- re-fetch the value feed every 30 min (0 = never)
    expectedPlaceId = 13200523806, -- Trading Plaza; auto-trade only runs here
  }
end

-- Deep-merge override onto base (base is not mutated). Tables recurse; scalars replace.
function M.merge(base, override)
  local out = {}
  for k, v in pairs(base) do
    if type(v) == "table" then out[k] = M.merge(v, {}) else out[k] = v end
  end
  if type(override) == "table" then
    for k, v in pairs(override) do
      if type(v) == "table" and type(out[k]) == "table" then
        out[k] = M.merge(out[k], v)
      else
        out[k] = v
      end
    end
  end
  return out
end

return M

end)()
__M["lib.pricing"] = (function()
local M = {}

local function round(n) return math.floor(n + 0.5) end

-- Returns { ask, ceiling, floor } for `qty` copies, or nil if unsellable.
-- feedEntry: { value?, demand?, naValue? }   override: { value?, markupPct?, bandPct? }
function M.quote(cfg, feedEntry, override, qty)
  override = override or {}
  qty = qty or 1
  local base = tonumber(override.value) or tonumber(feedEntry and feedEntry.value)
  if not base then return nil end  -- N/A and no override

  local markup = tonumber(override.markupPct) or cfg.globalMarkupPct or 0
  local band   = tonumber(override.bandPct)   or cfg.bandPct or 0
  local demand = tonumber(feedEntry and feedEntry.demand) or 0

  if cfg.demandScaling then
    -- demand 0..10 -> markup +0..+50% of itself; band shrinks up to -40%
    markup = markup * (1 + demand / 20)
    band   = band   * (1 - demand / 25)
  end

  local ask     = round(base * (1 + markup / 100)) * qty
  local ceiling = round(base * (1 + band / 100)) * qty
  local floor   = round(base * (1 - band / 100)) * qty
  return { ask = ask, ceiling = ceiling, floor = floor }
end

-- Buy-side quote for the auto-buyer (gem-cap mode).
-- Returns { max, floorBid } for `qty` copies, or nil if no base price.
--   max      = the most you'll pay (value * (1 - buyDiscount%), or explicit override)
--   floorBid = your opening lowball (max * (1 - band%))
function M.buyQuote(cfg, feedEntry, override, qty)
  override = override or {}
  qty = qty or 1
  local explicit = tonumber(override.maxBuyPrice)
  local base = explicit or tonumber(feedEntry and feedEntry.value)
  if not base then return nil end

  local band = tonumber(override.bandPct) or cfg.bandPct or 0
  local maxUnit
  if explicit then
    maxUnit = explicit
  else
    local discount = tonumber(override.buyDiscountPct) or cfg.buyDiscountPct or 0
    local demand = tonumber(feedEntry and feedEntry.demand) or 0
    if cfg.demandScaling then discount = discount * (1 - demand / 25) end -- high demand -> pay more
    maxUnit = base * (1 - discount / 100)
  end

  local max = round(maxUnit) * qty
  local floorBid = round(maxUnit * (1 - band / 100)) * qty
  return { max = max, floorBid = floorBid }
end

return M

end)()
__M["lib.negotiation"] = (function()
local M = {}

-- Current accept-threshold for a given round: starts at ceiling, steps down
-- toward floor by concedeStepPct of (ceiling-floor) per round, clamped at floor.
function M.threshold(cfg, quote, round)
  local step = (cfg.negotiation and cfg.negotiation.concedeStepPct or 0) / 100
  local span = quote.ceiling - quote.floor
  local t = quote.ceiling - span * step * (round or 0)
  if t < quote.floor then t = quote.floor end
  return math.floor(t + 0.5)
end

-- Decide the next move.
-- state: { offeredGems, targetChatNumber, round, elapsed }
-- Returns { action = "ACCEPT"|"COUNTER"|"HOLD"|"ABORT", amount?, message? }
function M.decide(cfg, quote, state)
  local maxRounds = cfg.negotiation and cfg.negotiation.maxRounds or 3
  local threshold = M.threshold(cfg, quote, state.round or 0)
  local offered = tonumber(state.offeredGems) or 0

  if offered >= threshold then
    return { action = "ACCEPT" }
  end

  local chat = tonumber(state.targetChatNumber)
  -- Out of rounds and still short -> give up.
  if (state.round or 0) >= maxRounds then
    return { action = "ABORT" }
  end

  if chat and chat >= quote.floor then
    -- counter toward the midpoint of their chat number and our threshold
    local counter = math.floor((chat + threshold) / 2 + 0.5)
    if counter < quote.floor then counter = quote.floor end
    if counter > quote.ceiling then counter = quote.ceiling end
    return { action = "COUNTER", amount = counter,
             message = ("I can do %d"):format(counter) }
  end

  if chat and chat < quote.floor then
    return { action = "ABORT" }
  end

  -- No usable signal yet: hold and wait for them to move.
  return { action = "HOLD" }
end

-- BUY side (auto-buyer). Threshold RISES from floorBid toward max over rounds.
function M.thresholdBuy(cfg, bq, round)
  local step = (cfg.negotiation and cfg.negotiation.concedeStepPct or 0) / 100
  local span = bq.max - bq.floorBid
  local t = bq.floorBid + span * step * (round or 0)
  if t > bq.max then t = bq.max end
  return math.floor(t + 0.5)
end

-- Decide the next BUY move.
-- state: { sellerAsk, round, elapsed }  (sellerAsk = gems the seller wants)
-- Returns { action = "ACCEPT"|"COUNTER"|"HOLD"|"ABORT", amount?, message? }
function M.decideBuy(cfg, bq, state)
  local maxRounds = cfg.negotiation and cfg.negotiation.maxRounds or 3
  local threshold = M.thresholdBuy(cfg, bq, state.round or 0)
  local ask = tonumber(state.sellerAsk)

  -- Seller wants no more than our current willingness -> buy.
  if ask and ask <= threshold then
    return { action = "ACCEPT" }
  end

  if (state.round or 0) >= maxRounds then
    return { action = "ABORT" }
  end

  if not ask then
    return { action = "HOLD" }
  end

  -- Counter upward, but never above our hard max.
  local bid
  if ask <= bq.max then
    bid = math.floor((threshold + ask) / 2 + 0.5)
  else
    bid = threshold           -- their ask exceeds our max; hold our line, keep trying
  end
  if bid > bq.max then bid = bq.max end
  if bid < bq.floorBid then bid = bq.floorBid end
  return { action = "COUNTER", amount = bid, message = ("I can pay %d"):format(bid) }
end

return M

end)()
__M["lib.ads"] = (function()
local M = {}

-- Short human form of a gem amount: 945000 -> "945k", 3675000 -> "3.7m",
-- 1000000 -> "1m", 810 -> "810". Always returns a single string.
function M.short(n)
  if n >= 1000000 then
    local s = ("%.1fm"):format(n / 1000000)
    s = (s:gsub("%.0m", "m"))
    return s
  elseif n >= 1000 then
    return ("%.0fk"):format(n / 1000)
  end
  return tostring(n)
end

-- Build a single advertisement line from listings { {name, ask}, ... }.
-- Returns nil when there is nothing to advertise.
function M.line(listings, opts)
  opts = opts or {}
  local maxItems = opts.maxItems or 5
  if #listings == 0 then return nil end
  local shown = math.min(maxItems, #listings)
  local parts = {}
  for i = 1, shown do
    parts[#parts + 1] = ("%s %s"):format(listings[i].name, M.short(listings[i].ask))
  end
  local msg = "Selling: " .. table.concat(parts, ", ")
  local omitted = #listings - shown
  if omitted > 0 then msg = msg .. (" +%d more"):format(omitted) end
  return msg .. " — msg me"
end

return M

end)()
__M["lib.capmode"] = (function()
local M = {}

-- Decide sell vs buy mode with hysteresis around the gem cap.
--   gems >= cap                    -> "buy"
--   in buy mode until gems drop below (cap - buffer), then "sell"
--   buyEnabled = false             -> always "sell"
function M.mode(cfg, gems, currentMode)
  gems = tonumber(gems) or 0
  if not cfg.buyEnabled then return "sell" end
  local cap = tonumber(cfg.gemCap) or math.huge
  local buffer = tonumber(cfg.gemCapBuffer) or 0
  if gems >= cap then return "buy" end
  if currentMode == "buy" and gems >= (cap - buffer) then return "buy" end
  return "sell"
end

return M

end)()
__M["lib.scamguard"] = (function()
local M = {}

-- Final safety check re-run in the same tick right before confirming a SELL:
-- the gems currently in the window must still meet the agreed threshold.
-- Defends against last-second offer swaps.
function M.safeToConfirmSell(agreedThreshold, currentOffered)
  local a = tonumber(agreedThreshold)
  local c = tonumber(currentOffered)
  if not a or not c then return false end
  return c >= a
end

-- Same idea for a BUY: the seller must not have raised what they want above
-- the amount we agreed to pay.
function M.safeToConfirmBuy(agreedPay, sellerWantsNow)
  local a = tonumber(agreedPay)
  local c = tonumber(sellerWantsNow)
  if not a or not c then return false end
  return c <= a
end

return M

end)()
__M["lib.cooldown"] = (function()
local M = {}

-- Per-player gate: blocklist first, then a min-seconds-between-trades cooldown.
-- Returns (allowed: bool, reason: string?).
function M.allow(cfg, player, lastTradeAt, now)
  if cfg.blocklist and player and cfg.blocklist[player] then
    return false, "blocked"
  end
  local cd = tonumber(cfg.cooldownSec) or 0
  if lastTradeAt and now and (now - lastTradeAt) < cd then
    return false, "cooldown"
  end
  return true, nil
end

return M

end)()
__M["lib.stats"] = (function()
local M = {}

function M.new(startTime)
  return { trades = 0, sells = 0, buys = 0, profit = 0,
           gemsIn = 0, gemsOut = 0, startTime = startTime or 0 }
end

-- Record a completed sell: received `gems`, item was worth `cost` to us.
function M.recordSell(s, gems, cost)
  gems = tonumber(gems) or 0
  cost = tonumber(cost) or 0
  s.trades = s.trades + 1
  s.sells = s.sells + 1
  s.gemsIn = s.gemsIn + gems
  s.profit = s.profit + (gems - cost)
  return s
end

-- Record a completed buy: paid `gems`.
function M.recordBuy(s, gems)
  gems = tonumber(gems) or 0
  s.trades = s.trades + 1
  s.buys = s.buys + 1
  s.gemsOut = s.gemsOut + gems
  s.profit = s.profit - gems
  return s
end

-- Profit per hour given the current time.
function M.profitPerHour(s, now)
  local dt = (tonumber(now) or 0) - (s.startTime or 0)
  if dt <= 0 then return 0 end
  return math.floor(s.profit / (dt / 3600) + 0.5)
end

return M

end)()
__M["lib.webhook"] = (function()
local M = {}

-- Build the Discord message content for an event, or nil for unknown events.
-- The actual HTTP POST is done by glue (runtime); this stays pure/testable.
function M.content(event, data)
  data = data or {}
  if event == "sale" then
    return ("Sold %s x%d for %s gems (profit %s)")
      :format(tostring(data.item or "?"), tonumber(data.qty) or 1,
              tostring(data.gems or 0), tostring(data.profit or 0))
  elseif event == "buy" then
    return ("Bought %s x%d for %s gems")
      :format(tostring(data.item or "?"), tonumber(data.qty) or 1, tostring(data.gems or 0))
  elseif event == "cap" then
    return ("Gem cap reached (%s). Switching to buy mode."):format(tostring(data.gems or 0))
  elseif event == "disconnect" then
    return "Disconnected - attempting reconnect..."
  elseif event == "reconnect" then
    return "Reconnected."
  elseif event == "error" then
    return ("Error: %s"):format(tostring(data.msg or "unknown"))
  end
  return nil
end

-- Whether this event should fire, based on config + a non-empty url.
function M.enabledFor(cfg, event)
  local w = cfg.webhook
  if not w or not w.url or w.url == "" then return false end
  if event == "sale" or event == "buy" then return w.onSale ~= false end
  if event == "cap" then return w.onCap ~= false end
  if event == "disconnect" or event == "reconnect" then return w.onDisconnect ~= false end
  if event == "error" then return w.onError ~= false end
  return false
end

return M

end)()
__M["lib.logbuf"] = (function()
local M = {}
M.__index = M

-- Ring buffer of timestamped log lines, plus a formatter for the debug report.
-- Pure: the caller supplies timestamps (os.clock/os.time) so this stays testable.
function M.new(capacity)
  return setmetatable({ cap = capacity or 400, lines = {}, counts = {} }, M)
end

-- level: "INFO" | "WARN" | "ERROR" | "OK" | "STEP"
function M:add(level, msg, t)
  level = level or "INFO"
  self.counts[level] = (self.counts[level] or 0) + 1
  local line = ("[%s] %-5s %s"):format(tostring(t or 0), level, tostring(msg))
  self.lines[#self.lines + 1] = line
  if #self.lines > self.cap then
    table.remove(self.lines, 1)
  end
  return line
end

function M:info(m, t)  return self:add("INFO", m, t) end
function M:warn(m, t)  return self:add("WARN", m, t) end
function M:err(m, t)   return self:add("ERROR", m, t) end
function M:ok(m, t)    return self:add("OK", m, t) end
function M:step(m, t)  return self:add("STEP", m, t) end

function M:errorCount() return self.counts["ERROR"] or 0 end

-- Render the full report with a header and a counts summary.
function M:report(header)
  local out = {}
  out[#out + 1] = "===== " .. (header or "AutoTrade Debug Report") .. " ====="
  local summary = {}
  for _, lvl in ipairs({ "STEP", "OK", "INFO", "WARN", "ERROR" }) do
    if self.counts[lvl] then summary[#summary + 1] = lvl .. "=" .. self.counts[lvl] end
  end
  out[#out + 1] = "summary: " .. table.concat(summary, " ")
  out[#out + 1] = "-----"
  for _, l in ipairs(self.lines) do out[#out + 1] = l end
  out[#out + 1] = "===== end ====="
  return table.concat(out, "\n")
end

return M

end)()
__M["lib.dump"] = (function()
local M = {}

-- Render a scalar/short description of any value.
function M.value(v)
  local ty = type(v)
  if ty == "string" then
    if #v > 60 then v = v:sub(1, 60) .. "..." end
    return '"' .. v .. '"'
  elseif ty == "number" or ty == "boolean" then
    return tostring(v)
  elseif ty == "table" then
    local n = 0
    for _ in pairs(v) do n = n + 1 end
    return ("table[%d]"):format(n)
  elseif ty == "function" then
    return "function"
  end
  return ty
end

-- Serialize a table's structure to a list of "key = value" lines, depth-limited.
-- opts: { maxDepth = 2, maxKeys = 40, indent = "  " }
function M.lines(t, opts)
  opts = opts or {}
  local maxDepth = opts.maxDepth or 2
  local maxKeys = opts.maxKeys or 40
  local indent = opts.indent or "  "
  local out = {}
  if type(t) ~= "table" then out[1] = M.value(t); return out end

  local function walk(tb, depth, prefix)
    local keys = {}
    for k in pairs(tb) do keys[#keys + 1] = k end
    table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
    local shown = 0
    for _, k in ipairs(keys) do
      shown = shown + 1
      if shown > maxKeys then
        out[#out + 1] = prefix .. "... (+" .. (#keys - maxKeys) .. " more keys)"
        break
      end
      local v = tb[k]
      out[#out + 1] = prefix .. tostring(k) .. " = " .. M.value(v)
      if type(v) == "table" and depth < maxDepth then
        walk(v, depth + 1, prefix .. indent)
      end
    end
    if #keys == 0 then out[#out + 1] = prefix .. "(empty)" end
  end

  walk(t, 1, "")
  return out
end

-- Convenience: joined string.
function M.text(t, opts)
  return table.concat(M.lines(t, opts), "\n")
end

return M

end)()
__M["lib.tradefields"] = (function()
-- Robust readers for the live activeTrade object. The game's exact field names
-- aren't fully confirmed, so we try known names first, then fuzzy-scan by keyword.
-- Each reader returns (value, fieldNameUsed) so the caller can log what matched.
local M = {}

local function firstKnown(at, names)
  for _, k in ipairs(names) do
    local v = tonumber(at[k])
    if v then return v, k end
  end
  return nil
end

local function fuzzyNumeric(at, mustA, mustB)
  for k, v in pairs(at) do
    if type(k) == "string" and type(v) == "number" then
      local lk = k:lower()
      if lk:find(mustA) and (not mustB or lk:find(mustB)) then return v, k end
    end
  end
  return nil
end

-- Gems the buyer (target/other player) has put into the window.
function M.buyerGems(at)
  if type(at) ~= "table" then return 0, nil end
  local v, k = firstKnown(at, { "sentGemsTarget", "offeredGemsTarget", "gemsTarget", "targetGems" })
  if v then return v, k end
  v, k = fuzzyNumeric(at, "gem", "target")
  if v then return v, k end
  return 0, nil
end

-- Gems we (the player) have put in.
function M.myGems(at)
  if type(at) ~= "table" then return 0, nil end
  local v, k = firstKnown(at, { "sentGemsPlayer", "offeredGemsPlayer", "gemsPlayer", "playerGems" })
  if v then return v, k end
  v, k = fuzzyNumeric(at, "gem", "player")
  if v then return v, k end
  return 0, nil
end

-- The other player's user id.
function M.partnerId(at)
  if type(at) ~= "table" then return nil end
  return at.targetID or at.targetId or at.partnerID or at.otherID or at.otherId
end

return M

end)()
__M["runtime.persist"] = (function()
-- Executor file persistence. All calls guarded: features degrade, never crash.
local HttpService = game:GetService("HttpService")
local M = {}
local FOLDER = "OdResto"
local SETTINGS = FOLDER .. "/autotrade_settings.json"
local FEEDCACHE = FOLDER .. "/value_cache.json"
local STATS = FOLDER .. "/autotrade_stats.json"

local function ensureFolder()
  if makefolder and (isfolder == nil or not isfolder(FOLDER)) then
    pcall(makefolder, FOLDER)
  end
end

local function readJson(path)
  if not (isfile and isfile(path) and readfile) then return nil end
  local ok, raw = pcall(readfile, path)
  if not ok then return nil end
  local ok2, tbl = pcall(function() return HttpService:JSONDecode(raw) end)
  return ok2 and tbl or nil
end

local function writeJson(path, tbl)
  if not writefile then return false end
  ensureFolder()
  local ok, raw = pcall(function() return HttpService:JSONEncode(tbl) end)
  if not ok then return false end
  return (pcall(writefile, path, raw))
end

function M.loadSettings() return readJson(SETTINGS) end
function M.saveSettings(tbl) return writeJson(SETTINGS, tbl) end
function M.loadFeedCache() return readJson(FEEDCACHE) end
function M.saveFeedCache(tbl) return writeJson(FEEDCACHE, tbl) end
function M.loadStats() return readJson(STATS) end
function M.saveStats(tbl) return writeJson(STATS, tbl) end

return M

end)()
__M["runtime.remotes"] = (function()
local Players = game:GetService("Players")
local M = {}

-- Core remotes the trade flow must have.
local REQUIRED = { "trading_acceptinvite", "trading_additem", "trading_removeitem",
                   "trading_confirmtrade", "trading_abort", "trading_sendmessage" }
-- Extra remotes used for status/invites/offers (looked up but not fatal if absent).
local OPTIONAL = { "trading_getstatus", "trading_invitesent", "trading_tradebegan",
                   "trading_statuschange", "trading_updategemoffer", "trading_unaccept",
                   "trading_cancelled", "trading_sendinvite" }

function M.resolveRemotes(timeout)
  timeout = timeout or 30

  local function tryParent(parent)
    if not parent then return nil end
    local things = parent:FindFirstChild("__THINGS")
    if not things then return nil end
    local remotes = things:FindFirstChild("__REMOTES")
    if not remotes then return nil end
    local out = { __container = remotes }
    for _, n in ipairs(REQUIRED) do
      local r = remotes:WaitForChild(n, timeout)
      if not r then return nil, "missing required remote " .. n end
      out[n] = r
    end
    for _, n in ipairs(OPTIONAL) do
      out[n] = remotes:FindFirstChild(n) -- may be nil
    end
    return out
  end

  pcall(function() workspace:WaitForChild("__THINGS", timeout) end)
  local out = tryParent(workspace)
  if out then return out, "workspace" end
  out = tryParent(Players.LocalPlayer)
  if out then return out, "localplayer" end

  local remotes
  pcall(function()
    for _, d in ipairs(game:GetDescendants()) do
      if d.Name == "__REMOTES" then remotes = d; break end
    end
  end)
  if remotes then
    local out2 = { __container = remotes }
    for _, n in ipairs(REQUIRED) do
      local r = remotes:FindFirstChild(n)
      if not r then return nil, "missing required remote " .. n .. " (via search)" end
      out2[n] = r
    end
    for _, n in ipairs(OPTIONAL) do out2[n] = remotes:FindFirstChild(n) end
    return out2, "search:" .. remotes:GetFullName()
  end
  return nil, "no __THINGS.__REMOTES found"
end

function M.loadBase(baseUrl)
  local ok, res = pcall(function() return loadstring(game:HttpGet(baseUrl))() end)
  return ok, res
end

function M.disableBaseSmartTradeFile()
  local ok = pcall(function()
    local HttpService = game:GetService("HttpService")
    local name = Players.LocalPlayer.Name
    local path = "OdResto/Trade-" .. name .. ".json"
    if isfile and isfile(path) and readfile and writefile then
      local t = HttpService:JSONDecode(readfile(path))
      t.smartTrade = false
      writefile(path, HttpService:JSONEncode(t))
    end
  end)
  return ok
end

return M

end)()
__M["runtime.gamedata"] = (function()
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")
local M = {}

-- Acquire the client Library module: require(Framework.Library).
function M.root(timeout)
  timeout = timeout or 30
  local ok, root = pcall(function()
    local fw = ReplicatedStorage:WaitForChild("Framework", timeout)
    local libmod = fw:WaitForChild("Library", timeout)
    return require(libmod)
  end)
  if ok and type(root) == "table" then return root end
  return nil, tostring(root)
end

-- Build a name -> itemID map from root.Directory.<category>, where each entry
-- is { ID = "156", name = "Wave Set", className = ..., ... }. Confirmed from the
-- live game dump. Non-item sub-tables (Tiers, goals) lack name+ID and are skipped.
function M.catalog(root)
  local cat = {}
  local dir = root and root.Directory
  if type(dir) == "table" then
    for _, ctbl in pairs(dir) do
      if type(ctbl) == "table" then
        for _, entry in pairs(ctbl) do
          if type(entry) == "table" then
            local id = entry.ID or entry.id or entry.itemID
            local name = entry.name or entry.Name
            if id and name then cat[name] = cat[name] or id end
          end
        end
      end
    end
  end
  cat.Wave = cat.Wave or "156"
  cat.Ocean = cat.Ocean or "50"
  return cat
end

-- Own gem balance: LocalPlayer.leaderstats.Gems.Value (report-confirmed).
function M.gems()
  local ok, v = pcall(function()
    local ls = Players.LocalPlayer:FindFirstChild("leaderstats")
    local g = ls and ls:FindFirstChild("Gems")
    return g and g.Value
  end)
  return (ok and tonumber(v)) or 0
end

-- Unwrap a status payload to the object holding incomingInvites/activeTrade.
-- The game wraps it one level deep ({ { status } }); handle both.
function M.unwrapStatus(a)
  if type(a) ~= "table" then return nil end
  if a.incomingInvites ~= nil or a.activeTrade ~= nil then return a end
  local inner = a[1]
  if type(inner) == "table" and (inner.incomingInvites ~= nil or inner.activeTrade ~= nil) then return inner end
  return nil
end

-- Current trade status via the trading_getstatus RemoteFunction (unwrapped).
function M.getStatus(remotes)
  local rf = remotes and remotes.trading_getstatus
  if not rf then return nil end
  local ok, res = pcall(function() return rf:InvokeServer() end)
  if not ok then return nil end
  return M.unwrapStatus(res)
end

return M

end)()
__M["runtime.inventory"] = (function()
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local M = {}

-- Returns { [SetName] = qty } for tradeable items the player owns.
-- Uses the game's Framework.Library, mirroring how the base reads inventory.
-- CONFIRM IN-GAME: the exact Library accessor + entry shape (see Task 10 checklist).
function M.owned()
  local out = {}
  local ok = pcall(function()
    local fw = ReplicatedStorage:WaitForChild("Framework", 10)
    local Library = require(fw):Library()          -- shape confirmed in-game
    local inv = Library.Inventory or (Library.GetInventory and Library:GetInventory())
    if type(inv) ~= "table" then return end
    for _, entry in pairs(inv) do
      if type(entry) == "table" then
        local name = entry.class or entry.Name
        if name then
          out[name] = (out[name] or 0) + (entry.count or entry.targetQty or 1)
        end
      end
    end
  end)
  if not ok then return {} end
  return out
end

return M

end)()
__M["runtime.prober"] = (function()
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local dump = __M["lib.dump"]
local M = {}

local function has(fn) return type(fn) == "function" end

-- Run a probe; if it errors, LOG the error (never silently swallow).
local function safe(log, label, t, fn)
  local ok, err = pcall(fn)
  if not ok then log:err(label .. " probe FAILED: " .. tostring(err), t) end
end

-- Log a table dump as multiple indented INFO lines.
local function logDump(log, label, tbl, t, opts)
  log:info(label .. ":", t)
  for _, line in ipairs(dump.lines(tbl, opts)) do log:info("  " .. line, t) end
end

function M.run(log, t)
  local lp = Players.LocalPlayer

  safe(log, "executor", t, function()
    local name = (identifyexecutor and identifyexecutor()) or (getexecutorname and getexecutorname()) or "unknown"
    log:info("executor: " .. tostring(name), t)
    log:info("caps: http=" .. tostring(has(http_request) or has(request))
      .. " clipboard=" .. tostring(has(setclipboard) or has(toclipboard))
      .. " files=" .. tostring(has(writefile) and has(readfile)), t)
    log:info(("place=%s job=%s player=%s"):format(tostring(game.PlaceId), tostring(game.JobId), tostring(lp and lp.Name)), t)
  end)

  -- REMOTES: base uses workspace.__THINGS.__REMOTES; check workspace then LocalPlayer.
  safe(log, "remotes", t, function()
    local function dumpRemotes(parent, label)
      local things = parent and parent:FindFirstChild("__THINGS")
      if not things then log:info(label .. ".__THINGS: not found", t); return false end
      local remotes = things:FindFirstChild("__REMOTES")
      if not remotes then log:warn(label .. ".__THINGS has no __REMOTES", t); return false end
      local names = {}
      for _, c in ipairs(remotes:GetChildren()) do names[#names + 1] = c.Name .. "(" .. c.ClassName .. ")" end
      log:ok(("__REMOTES @ %s [%d]: %s"):format(label, #names, table.concat(names, ", ")), t)
      return true
    end
    if not dumpRemotes(workspace, "workspace") and not dumpRemotes(lp, "LocalPlayer") then
      log:warn("searching all descendants for __REMOTES...", t)
      local found = 0
      for _, d in ipairs(game:GetDescendants()) do
        if d.Name == "__REMOTES" then log:ok("found __REMOTES at: " .. d:GetFullName(), t); found = found + 1 end
      end
      if found == 0 then log:err("NO __REMOTES anywhere in the game", t) end
    end
  end)

  -- LEADERSTATS + Gems
  safe(log, "leaderstats", t, function()
    local ls = lp:FindFirstChild("leaderstats")
    if not ls then log:warn("no leaderstats", t); return end
    for _, v in ipairs(ls:GetChildren()) do log:info("leaderstats." .. v.Name .. " = " .. tostring(v.Value), t) end
    local g = ls:FindFirstChild("Gems")
    if g then log:ok("GEMS = " .. tostring(g.Value), t) else log:warn("no leaderstats.Gems (cap mode needs it)", t) end
  end)

  -- FRAMEWORK -> Library root (trade data + item catalog)
  safe(log, "framework", t, function()
    local fw = ReplicatedStorage:FindFirstChild("Framework")
    if not fw then log:err("no ReplicatedStorage.Framework", t); return end
    log:ok("Framework present (" .. fw.ClassName .. ")", t)
    local kids = {}
    for _, c in ipairs(fw:GetChildren()) do kids[#kids + 1] = c.Name .. "(" .. c.ClassName .. ")" end
    log:info("Framework children: " .. table.concat(kids, ", "), t)

    local libmod = fw:FindFirstChild("Library")
    if not libmod then log:err("no Framework.Library child (base requires this)", t); return end
    local ok, root = pcall(require, libmod)
    if not ok then log:err("require(Framework.Library) errored: " .. tostring(root), t); return end
    if type(root) ~= "table" then log:err("Library returned " .. type(root) .. " (expected table)", t); return end

    logDump(log, "Library root keys", root, t, { maxDepth = 1, maxKeys = 70 })

    -- Item categories: dump a few sample entries so we can find the id field.
    for _, catego in ipairs({ "Furniture", "Appliance", "Directory", "Inventory", "Food" }) do
      local tbl = root[catego]
      if type(tbl) == "table" then
        local n = 0
        for k, v in pairs(tbl) do
          n = n + 1
          if n <= 3 then logDump(log, catego .. "[" .. tostring(k) .. "]", (type(v) == "table" and v) or { value = v }, t, { maxDepth = 2 }) end
        end
        log:ok(catego .. " count = " .. n, t)
      end
    end
  end)

  -- chat channel
  safe(log, "chat", t, function()
    local tcs = game:GetService("TextChatService")
    local chans = tcs:FindFirstChild("TextChannels")
    local rbx = chans and chans:FindFirstChild("RBXGeneral")
    log:info("RBXGeneral channel present: " .. tostring(rbx ~= nil), t)
  end)
end

return M

end)()
__M["runtime.webhook_send"] = (function()
local HttpService = game:GetService("HttpService")
local webhook = __M["lib.webhook"]
local M = {}

local function httpPost(url, jsonBody)
  local req = http_request or request or (syn and syn.request) or (fluxus and fluxus.request)
  if not req then return false end
  return (pcall(function()
    req({
      Url = url,
      Method = "POST",
      Headers = { ["Content-Type"] = "application/json" },
      Body = jsonBody,
    })
  end))
end

-- send(cfg, event, data) -> bool. No-op unless the event is enabled + url set.
function M.send(cfg, event, data)
  if not webhook.enabledFor(cfg, event) then return false end
  local content = webhook.content(event, data)
  if not content then return false end
  local ok, body = pcall(function() return HttpService:JSONEncode({ content = content }) end)
  if not ok then return false end
  return httpPost(cfg.webhook.url, body)
end

return M

end)()
__M["runtime.survival"] = (function()
local Players = game:GetService("Players")
local M = {}

-- Anti-AFK: defeat the 20-minute idle kick via VirtualUser on the Idled signal.
function M.startAntiAfk(cfg)
  if not (cfg.survival and cfg.survival.antiAfk) then return end
  pcall(function()
    local VirtualUser = game:GetService("VirtualUser")
    Players.LocalPlayer.Idled:Connect(function()
      pcall(function()
        VirtualUser:CaptureController()
        VirtualUser:ClickButton2(Vector2.new())
      end)
    end)
  end)
end

-- Auto-reconnect: on a disconnect/kick error, rejoin the same place.
-- CONFIRM IN-GAME: the exact disconnect signal your executor surfaces.
function M.startReconnect(cfg, onEvent)
  if not (cfg.survival and cfg.survival.autoReconnect) then return end
  pcall(function()
    local GuiService = game:GetService("GuiService")
    local TeleportService = game:GetService("TeleportService")
    GuiService.ErrorMessageChanged:Connect(function(msg)
      if onEvent then onEvent("disconnect", { msg = tostring(msg) }) end
      task.wait(1)
      pcall(function() TeleportService:Teleport(game.PlaceId, Players.LocalPlayer) end)
    end)
  end)
end

-- Watchdog: run `fn` in a loop; if it errors, report + retry up to maxErrors.
function M.watchdog(cfg, name, fn, onEvent)
  if not (cfg.survival and cfg.survival.watchdog) then
    task.spawn(fn); return
  end
  task.spawn(function()
    local errs = 0
    while true do
      local ok, err = pcall(fn)
      if ok then break end
      errs = errs + 1
      if onEvent then onEvent("error", { msg = name .. ": " .. tostring(err) }) end
      if errs >= (cfg.survival.watchdogMaxErrors or 5) then break end
      task.wait(2)
    end
  end)
end

return M

end)()
__M["runtime.trade"] = (function()
local pricing = __M["lib.pricing"]
local negotiation = __M["lib.negotiation"]
local scamguard = __M["lib.scamguard"]
local tf = __M["lib.tradefields"]

local M = {}

-- deps: { remotes, cfg, feed, catalog, getActiveTrade, pickSellItem, pickBuyItem,
--         sendTradeMsg, log, mode, onSold, onBought }
function M.new(deps) return setmetatable({ d = deps, busy = false, loggedField = false }, { __index = M }) end

-- Robust buyer-gems read; logs which field matched, once.
function M:buyerGems(at)
  local g, field = tf.buyerGems(at)
  if field and not self.loggedField then
    self.loggedField = true
    self.d.log("buyer-gems field = '" .. tostring(field) .. "'")
  end
  return g
end

function M:handle(invite)
  if self.busy then return end
  self.busy = true
  local ok, err = pcall(function()
    if self.d.mode and self.d.mode() == "buy" and self.d.cfg.buyEnabled then
      self:runBuy(invite)
    else
      self:runSell(invite)
    end
  end)
  if not ok then self:abort("error: " .. tostring(err)) end
  self.busy = false
end

function M:accept(invite)
  local who = (type(invite) == "table" and (invite.player or invite.uid)) or invite
  self.d.remotes.trading_acceptinvite:FireServer(who)
  self.d.log("accepted invite (" .. tostring((type(invite) == "table" and invite.name) or who) .. ")")
end

function M:waitForTrade(timeout)
  local start = os.time()
  repeat
    local at = self.d.getActiveTrade()
    if type(at) == "table" then return at end
    task.wait(0.4)
  until os.time() - start > (timeout or 60)
  return self.d.getActiveTrade()
end

-- ---- SELL -------------------------------------------------------------------
function M:runSell(invite)
  local d = self.d
  self:accept(invite)
  local at = self:waitForTrade(d.cfg.tradeTimeoutSec)
  if not at then return self:abort("no active trade after accept") end

  local setName = d.pickSellItem and d.pickSellItem(at)
  if not setName then return self:abort("no vend item set (pick an Active Vend Item / mark one For Sale)") end

  local feedEntry = d.feed[setName]
  local override = (d.cfg.items or {})[setName] or {}
  local quote = pricing.quote(d.cfg, feedEntry or {}, override, 1)
  if not quote then return self:abort("unpriceable: " .. setName) end

  -- HARD FLOOR from the real market value, independent of any override.
  local marketVal = feedEntry and tonumber(feedEntry.value)
  local hardFloor = marketVal and math.floor(marketVal * (d.cfg.minSellPct or 90) / 100) or quote.floor

  self:addItem(setName, 1)
  if d.sendTradeMsg then
    d.sendTradeMsg(("Selling %s for %s gems - add gems and confirm!"):format(setName, tostring(quote.ask)))
  end
  d.log(("SELL %s | ask %s ceiling %s floor %s hardFloor %s | buyer has %s")
    :format(setName, tostring(quote.ask), tostring(quote.ceiling), tostring(quote.floor), tostring(hardFloor), tostring(self:buyerGems(at))))

  local start = os.time()
  for round = 0, (d.cfg.negotiation.maxRounds or 3) do
    local cur = d.getActiveTrade() or at
    local bg = self:buyerGems(cur)
    local decision = negotiation.decide(d.cfg, quote, { offeredGems = bg, round = round, elapsed = os.time() - start })
    d.log(("round %d: buyer=%s decision=%s"):format(round, tostring(bg), decision.action))

    if decision.action == "ACCEPT" then
      local fresh = d.getActiveTrade() or cur
      local fg = self:buyerGems(fresh)
      local required = math.max(negotiation.threshold(d.cfg, quote, round), hardFloor)
      if fg < required then
        return self:abort(("safety: buyer %s < required %s (hardFloor %s)"):format(tostring(fg), tostring(required), tostring(hardFloor)))
      end
      if d.cfg.testMode then
        d.log(("TEST MODE: WOULD SELL %s for %s gems - not confirming"):format(setName, tostring(fg)))
        task.wait(1)
        return self:abort("test mode (no confirm)")
      end
      d.remotes.trading_confirmtrade:FireServer()
      local cost = (marketVal or 0)
      if d.onSold then d.onSold(setName, 1, fg, cost) end
      return
    elseif decision.action == "COUNTER" then
      if d.sendTradeMsg then d.sendTradeMsg(decision.message) end
      task.wait(d.cfg.negotiation.chatCooldownSec or 4)
    elseif decision.action == "ABORT" then
      return self:abort("buyer offer too low")
    else
      task.wait(2)
    end
    if os.time() - start > (d.cfg.tradeTimeoutSec or 60) then return self:abort("timeout") end
  end
  return self:abort("max rounds")
end

-- ---- BUY (gem-cap mode) -----------------------------------------------------
function M:runBuy(invite)
  local d = self.d
  self:accept(invite)
  local at = self:waitForTrade(d.cfg.tradeTimeoutSec)
  if not at then return self:abort("buy: no active trade") end

  local setName = d.pickBuyItem and d.pickBuyItem(at)
  if not setName then return self:abort("buy: item not on buy list") end
  local feedEntry = d.feed[setName]
  local wantEntry = (d.cfg.buy or {})[setName] or {}
  local bq = pricing.buyQuote(d.cfg, feedEntry or {}, wantEntry, 1)
  if not bq then return self:abort("no buy price: " .. setName) end

  local start = os.time()
  for round = 0, (d.cfg.negotiation.maxRounds or 3) do
    local cur = d.getActiveTrade() or at
    local ask = self:buyerGems(cur)
    local decision = negotiation.decideBuy(d.cfg, bq, { sellerAsk = ask, round = round, elapsed = os.time() - start })
    if decision.action == "ACCEPT" then
      local fresh = d.getActiveTrade() or cur
      if not scamguard.safeToConfirmBuy(bq.max, self:buyerGems(fresh)) then
        return self:abort("scam-guard: seller raised price")
      end
      if d.cfg.testMode then
        d.log(("TEST MODE: WOULD BUY %s for %s - not confirming"):format(setName, tostring(self:buyerGems(fresh))))
        return self:abort("test mode (no confirm)")
      end
      d.remotes.trading_confirmtrade:FireServer()
      if d.onBought then d.onBought(setName, 1, self:buyerGems(fresh)) end
      return
    elseif decision.action == "COUNTER" then
      if d.sendTradeMsg then d.sendTradeMsg(decision.message) end
      task.wait(d.cfg.negotiation.chatCooldownSec or 4)
    elseif decision.action == "ABORT" then
      return self:abort("buy negotiation failed")
    else
      task.wait(2)
    end
    if os.time() - start > (d.cfg.tradeTimeoutSec or 60) then return self:abort("timeout") end
  end
  return self:abort("buy max rounds")
end

-- ---- shared -----------------------------------------------------------------
function M:addItem(setName, qty)
  local id = self.d.catalog[setName]
  if not id then self.d.log("no itemID for '" .. tostring(setName) .. "' - cannot add"); return end
  local descriptor = { { itemID = tostring(id), className = setName } }
  self.d.remotes.trading_additem:FireServer(descriptor)
  self.d.log(("added %s (id %s)"):format(setName, tostring(id)))
end

function M:abort(reason)
  pcall(function() self.d.remotes.trading_abort:FireServer() end)
  self.d.log("Aborted: " .. reason)
end

return M

end)()
__M["runtime.advertiser"] = (function()
local Players = game:GetService("Players")
local TextChatService = game:GetService("TextChatService")
local ads = __M["lib.ads"]
local pricing = __M["lib.pricing"]
local M = {}

-- Post to the public RBXGeneral channel. Returns (ok, err) so callers can log.
local function sendChat(text)
  local ok, err = pcall(function()
    local ch = TextChatService:WaitForChild("TextChannels", 5):WaitForChild("RBXGeneral", 5)
    ch:SendAsync(text)
  end)
  return ok, err
end
M.sendChat = sendChat

local function buildListings(cfg, feed, owned)
  local listings = {}
  for name, override in pairs(cfg.items or {}) do
    if override.forSale then
      if (not owned) or (owned[name] and owned[name] > 0) then
        local q = pricing.quote(cfg, feed[name] or {}, override, 1)
        if q then listings[#listings + 1] = { name = name, ask = q.ask } end
      end
    end
  end
  return listings
end
M.buildListings = buildListings

-- deps: { cfg, feed, ownedFn, log }
function M.start(deps)
  local cfg = deps.cfg
  local warnedOff = false
  task.spawn(function()
    while true do
      if cfg.enabled and cfg.ads.rotatingAds then
        warnedOff = false
        local owned = cfg.ads.stockOnly and deps.ownedFn() or nil
        local listings = buildListings(cfg, deps.feed, owned)
        local line = ads.line(listings, { maxItems = 5 })
        if line then
          local ok, err = sendChat(line)
          deps.log(ok and ("Ad sent: " .. line) or ("Ad FAILED (chat): " .. tostring(err)))
        else
          deps.log("Ad skipped: nothing marked For Sale (in stock)")
        end
      elseif cfg.enabled and not cfg.ads.rotatingAds and not warnedOff then
        warnedOff = true
        deps.log("Ads OFF (turn on 'Rotating Chat Ads' to advertise)")
      end
      if cfg.enabled and cfg.ads.autoInvite then
        pcall(function()
          for _, plr in ipairs(Players:GetPlayers()) do
            if plr ~= Players.LocalPlayer then
              -- CONFIRM IN-GAME: the game's trade-invite request path.
            end
          end
        end)
      end
      task.wait(math.max(20, cfg.ads.intervalSec or 45))
    end
  end)
end

return M

end)()
__M["runtime.ui"] = (function()
local M = {}

local WINDUI_URL = "https://github.com/Footagesus/WindUI/releases/latest/download/main.lua"

-- Build a self-contained WindUI window for the layer. Independent of the base
-- (the base's own window handle is locked inside its obfuscated VM).
-- deps: { cfg, feed, save, stats, onToggleEnabled }
-- Returns the window handle (with :setStatus) or nil on failure.
function M.build(deps)
  local cfg, save = deps.cfg, deps.save
  local ok, WindUI = pcall(function()
    return loadstring(game:HttpGet(WINDUI_URL))()
  end)
  if not ok or not WindUI then return nil end

  local Window = WindUI:CreateWindow({
    Title = "Universal Auto-Trade",
    Icon = "arrows-exchange",
    Author = "by 0xfray",
    Folder = "OdResto",
    Size = UDim2.fromOffset(580, 520),
    Transparent = true,
    Theme = "Dark",
  })

  local Main = Window:Tab({ Title = "Auto-Trade", Icon = "coins" })
  local Items = Window:Tab({ Title = "Items", Icon = "list" })
  local Safety = Window:Tab({ Title = "24/7 & Safety", Icon = "shield" })
  local Diag = Window:Tab({ Title = "Diagnostics", Icon = "bug" })

  local statusParagraph = Main:Paragraph({
    Title = "Status", Desc = "Idle - not enabled.",
  })

  -- ---- Diagnostics tab ----
  Diag:Paragraph({ Title = "Debug report",
    Desc = "Press Copy, then paste it back to get help. It lists remotes, gem sources, and boot steps." })
  Diag:Button({ Title = "Copy Debug Report", Icon = "clipboard-copy",
    Callback = function()
      local copied = deps.debug and deps.debug.copy and deps.debug.copy()
      pcall(function()
        WindUI:Notify({ Title = "Auto-Trade",
          Content = copied and "Copied! Paste it back." or "Printed to console (no clipboard).",
          Duration = 5 })
      end)
    end })
  Diag:Button({ Title = "Print Debug Report to Console", Icon = "terminal",
    Callback = function() if deps.debug and deps.debug.print then deps.debug.print() end end })

  -- ---- Main tab ----
  Main:Toggle({ Title = "Enable Universal Auto-Trade", Value = cfg.enabled,
    Callback = function(v) cfg.enabled = v; save(cfg); if deps.onToggleEnabled then deps.onToggleEnabled(v) end end })
  Main:Toggle({ Title = "Test Mode (accepts + adds item, never confirms)", Value = cfg.testMode ~= false,
    Callback = function(v) cfg.testMode = v; save(cfg) end })

  -- Active vend item: the single item the bot sells in every trade.
  local vendNames = { "(highest-value For Sale)" }
  do
    local ns = {}
    for name in pairs(deps.feed) do ns[#ns + 1] = name end
    table.sort(ns)
    for _, n in ipairs(ns) do vendNames[#vendNames + 1] = n end
  end
  Main:Dropdown({ Title = "Active Vend Item (what it sells)", Values = vendNames,
    Value = (cfg.activeVendItem ~= "" and cfg.activeVendItem) or vendNames[1],
    Callback = function(sel)
      if sel == vendNames[1] then cfg.activeVendItem = "" else
        cfg.activeVendItem = sel
        cfg.items[sel] = cfg.items[sel] or {}; cfg.items[sel].forSale = true
      end
      save(cfg)
    end })
  Main:Slider({ Title = "Global Markup %", Step = 1,
    Value = { Min = 0, Max = 50, Default = cfg.globalMarkupPct },
    Callback = function(v) cfg.globalMarkupPct = v; save(cfg) end })
  Main:Slider({ Title = "Negotiation Band %", Step = 1,
    Value = { Min = 0, Max = 30, Default = cfg.bandPct },
    Callback = function(v) cfg.bandPct = v; save(cfg) end })
  Main:Toggle({ Title = "Demand Scaling", Value = cfg.demandScaling,
    Callback = function(v) cfg.demandScaling = v; save(cfg) end })
  Main:Dropdown({ Title = "Trade Unit Mode",
    Values = { "single_copy", "single_type_qty", "multi_basket" },
    Value = cfg.tradeUnitMode,
    Callback = function(v) cfg.tradeUnitMode = v; save(cfg) end })
  Main:Toggle({ Title = "Rotating Chat Ads", Value = cfg.ads.rotatingAds,
    Callback = function(v) cfg.ads.rotatingAds = v; save(cfg) end })
  Main:Toggle({ Title = "Auto-Invite Nearby", Value = cfg.ads.autoInvite,
    Callback = function(v) cfg.ads.autoInvite = v; save(cfg) end })
  Main:Toggle({ Title = "Ads: In-Stock Only", Value = cfg.ads.stockOnly,
    Callback = function(v) cfg.ads.stockOnly = v; save(cfg) end })

  -- ---- Items tab (per-item for-sale + overrides) ----
  local names = {}
  for name in pairs(deps.feed) do names[#names + 1] = name end
  table.sort(names)
  local selected = names[1]
  Items:Dropdown({ Title = "Select Item", Values = names, Value = names[1],
    Callback = function(sel) selected = sel end })
  Items:Toggle({ Title = "Selected: For Sale", Value = false,
    Callback = function(v)
      if not selected then return end
      cfg.items[selected] = cfg.items[selected] or {}
      cfg.items[selected].forSale = v; save(cfg) end })
  Items:Input({ Title = "Selected: Price Override (blank = use value)",
    Callback = function(txt)
      if not selected then return end
      cfg.items[selected] = cfg.items[selected] or {}
      cfg.items[selected].value = tonumber(txt); save(cfg) end })
  Items:Toggle({ Title = "Selected: Want to Buy (cap mode)", Value = false,
    Callback = function(v)
      if not selected then return end
      cfg.buy[selected] = cfg.buy[selected] or {}
      cfg.buy[selected].wantBuy = v; save(cfg) end })

  -- ---- Safety / 24-7 tab ----
  Safety:Toggle({ Title = "Auto-Buyer at Gem Cap", Value = cfg.buyEnabled,
    Callback = function(v) cfg.buyEnabled = v; save(cfg) end })
  Safety:Input({ Title = "Gem Cap (default 100000000)",
    Callback = function(txt) cfg.gemCap = tonumber(txt) or cfg.gemCap; save(cfg) end })
  Safety:Input({ Title = "Buy Discount % (default 10)",
    Callback = function(txt) cfg.buyDiscountPct = tonumber(txt) or cfg.buyDiscountPct; save(cfg) end })
  Safety:Input({ Title = "Player Cooldown sec (default 30)",
    Callback = function(txt) cfg.cooldownSec = tonumber(txt) or cfg.cooldownSec; save(cfg) end })
  Safety:Toggle({ Title = "Auto-Reconnect", Value = cfg.survival.autoReconnect,
    Callback = function(v) cfg.survival.autoReconnect = v; save(cfg) end })
  Safety:Toggle({ Title = "Anti-AFK", Value = cfg.survival.antiAfk,
    Callback = function(v) cfg.survival.antiAfk = v; save(cfg) end })
  Safety:Input({ Title = "Discord Webhook URL (blank = off)",
    Callback = function(txt) cfg.webhook.url = txt or ""; save(cfg) end })

  local handle = { window = Window, status = statusParagraph }
  function handle.setStatus(text)
    pcall(function() statusParagraph:SetDesc(text) end)
  end
  function handle.notify(text)
    pcall(function() WindUI:Notify({ Title = "Auto-Trade", Content = text, Duration = 8 }) end)
  end
  return handle
end

return M

end)()
-- === main ===
-- Universal Auto-Trade - STANDALONE. Does not load the obfuscated base; it talks
-- to the game directly (workspace.__THINGS.__REMOTES + Framework.Library) and
-- builds its own WindUI window. Only external deps: WindUI + the value feed.
local CONFIG = {
  feedUrl = "https://raw.githubusercontent.com/0xfray/Mr-script/refs/heads/main/MR/value.lua",
  version = "v1.3-standalone",
}

local libConfig  = __M["lib.config"]
local libFeed    = __M["lib.feed"]
local capmode    = __M["lib.capmode"]
local libStats   = __M["lib.stats"]
local LogBuf     = __M["lib.logbuf"]
local dump       = __M["lib.dump"]
local remotesM   = __M["runtime.remotes"]
local gamedata   = __M["runtime.gamedata"]
local persist    = __M["runtime.persist"]
local inventory  = __M["runtime.inventory"]
local prober     = __M["runtime.prober"]
local TradeM     = __M["runtime.trade"]
local advertiser = __M["runtime.advertiser"]
local survival   = __M["runtime.survival"]
local webhookSend= __M["runtime.webhook_send"]
local cooldownLib= __M["lib.cooldown"]
local ui         = __M["runtime.ui"]

local dbg = LogBuf.new(600)
local function nows() return string.format("%.2fs", os.clock()) end
local function logp(t) print("[AutoTrade] " .. t); dbg:info(t, nows()) end
local function logstep(t) print("[AutoTrade] * " .. t); dbg:step(t, nows()) end
local function logwarn(t) warn("[AutoTrade] " .. t); dbg:warn(t, nows()) end
local function logok(t) print("[AutoTrade] OK " .. t); dbg:ok(t, nows()) end
local function logDump(label, tbl) dbg:info(label .. ":", nows()); for _, l in ipairs(dump.lines(tbl, { maxDepth = 3, maxKeys = 40 })) do dbg:info("  " .. l, nows()) end end

logstep("boot " .. CONFIG.version)

local cfg = libConfig.merge(libConfig.defaults(), persist.loadSettings() or {})
logok("settings loaded (enabled=" .. tostring(cfg.enabled) .. ")")

local function fetchFeed()
  local ok, raw = pcall(function() return loadstring(game:HttpGet(CONFIG.feedUrl))() end)
  if ok and type(raw) == "table" then persist.saveFeedCache(raw); return libFeed.normalize(raw) end
  return nil, raw
end
local feed, feedErr = fetchFeed()
if feed then logok("feed fetched (" .. libFeed.count(feed) .. " items)")
else feed = libFeed.normalize(persist.loadFeedCache() or {})
  logwarn("feed fetch failed (" .. tostring(feedErr) .. "); cache=" .. libFeed.count(feed) .. " items") end

local statsObj = persist.loadStats() or libStats.new(os.time())
local function onEvent(event, data) pcall(webhookSend.send, cfg, event, data) end

local function copyReport()
  local r = dbg:report("AutoTrade " .. CONFIG.version)
  if setclipboard then pcall(setclipboard, r) elseif toclipboard then pcall(toclipboard, r) end
  print(r)
end
local uiHandle = ui.build({ cfg = cfg, feed = feed, save = persist.saveSettings, stats = statsObj,
  debug = { copy = copyReport, print = function() print(dbg:report("AutoTrade " .. CONFIG.version)) end },
  onToggleEnabled = function() end })
if uiHandle then logok("WindUI panel loaded") else logwarn("WindUI panel FAILED to load") end
local function setStatus(t) if uiHandle and uiHandle.setStatus then uiHandle.setStatus(t) end end

local wrongPlace = cfg.expectedPlaceId and game.PlaceId ~= cfg.expectedPlaceId
local remotes, rroot
if wrongPlace then
  logwarn(("WRONG GAME: place=%s (need Trading Plaza %s)"):format(tostring(game.PlaceId), tostring(cfg.expectedPlaceId)))
  setStatus("Wrong game. Open Trading Plaza (13200523806), then reload.")
  if uiHandle and uiHandle.notify then uiHandle.notify("Open Trading Plaza to trade.") end
else
  setStatus("Connecting to game...")
  logstep("resolving remotes (workspace.__THINGS.__REMOTES)")
  local rerr; remotes, rerr = remotesM.resolveRemotes(20)
  if remotes then logok("remotes resolved via " .. tostring(rerr)) else logwarn("remotes NOT resolved: " .. tostring(rerr)) end
  logstep("acquiring Framework Library root")
  local rooterr; rroot, rooterr = gamedata.root(20)
  if rroot then logok("Library root acquired") else logwarn("Library root FAILED: " .. tostring(rooterr)) end
end

logstep("probing environment"); pcall(function() prober.run(dbg, nows()) end); logok("probe complete")

survival.startAntiAfk(cfg); survival.startReconnect(cfg, onEvent)
logok("survival started")

if remotes and rroot then
  local catalog = gamedata.catalog(rroot)
  local catCount = 0; for _ in pairs(catalog) do catCount = catCount + 1 end
  logok("item catalog built (" .. tostring(catCount) .. " ids)")
  if catCount <= 4 then logwarn("catalog nearly empty - additem will only work for Wave/Ocean until the id source is confirmed") end

  local latestStatus
  local dumpedStatus, dumpedAT, dumpedInvite = false, false, false
  local function getActiveTrade() return latestStatus and latestStatus.activeTrade end
  local function getGems() return gamedata.gems() end
  local function sendTradeMsg(text) pcall(function() remotes.trading_sendmessage:FireServer(text) end) end

  local cooldownState = {}
  local function gate(name)
    local t = os.time(); local okg = cooldownLib.allow(cfg, name, cooldownState[name], t)
    if okg then cooldownState[name] = t end; return okg
  end
  local lastMode = "sell"
  local function mode()
    local gems = getGems(); local m = capmode.mode(cfg, gems, lastMode)
    if m ~= lastMode then
      logp(("mode %s -> %s (gems=%s cap=%s buyEnabled=%s)"):format(lastMode, m, tostring(gems), tostring(cfg.gemCap), tostring(cfg.buyEnabled)))
    end
    if m == "buy" and lastMode ~= "buy" then onEvent("cap", { gems = gems }) end
    lastMode = m; return m
  end
  -- Sell the configured Active Vend Item; else the highest-value For Sale item.
  local function pickSellItem(_at)
    if cfg.activeVendItem and cfg.activeVendItem ~= "" then return cfg.activeVendItem end
    local best, bestVal
    for name, ov in pairs(cfg.items or {}) do
      if ov.forSale then
        local v = (feed[name] and feed[name].value) or 0
        if not bestVal or v > bestVal then best = name; bestVal = v end
      end
    end
    return best
  end
  local function pickBuyItem(at)
    local offered = at and (at.offeredItemsTarget)
    if type(offered) == "table" then for _, it in pairs(offered) do local c = (type(it) == "table" and (it.class or it.className or it.name)) or it; if c and cfg.buy[c] and cfg.buy[c].wantBuy then return c end end end
    return nil
  end
  local function onSold(item, qty, gems, cost)
    libStats.recordSell(statsObj, gems, cost); persist.saveStats(statsObj)
    onEvent("sale", { item = item, qty = qty, gems = gems, profit = gems - cost })
    logp(("SOLD %s x%d for %s"):format(item, qty, tostring(gems))); setStatus(("Sold %s x%d for %s"):format(item, qty, tostring(gems)))
  end
  local function onBought(item, qty, gems)
    libStats.recordBuy(statsObj, gems); persist.saveStats(statsObj)
    onEvent("buy", { item = item, qty = qty, gems = gems })
    logp(("BOUGHT %s x%d for %s"):format(item, qty, tostring(gems))); setStatus(("Bought %s x%d for %s"):format(item, qty, tostring(gems)))
  end

  local runner = TradeM.new({
    remotes = remotes, cfg = cfg, feed = feed, catalog = catalog,
    getActiveTrade = getActiveTrade, sendTradeMsg = sendTradeMsg,
    pickSellItem = pickSellItem, pickBuyItem = pickBuyItem,
    log = logp, mode = mode, gate = gate, onSold = onSold, onBought = onBought,
  })

  -- Single gated entry point for accepting an invite. gate() dedups both the
  -- poll path and the event path (per-player cooldown), so no double-processing.
  local function playerName(p)
    if type(p) == "userdata" then local ok, n = pcall(function() return p.Name end); return ok and n or "?" end
    return tostring(p)
  end
  local function tryHandleInvite(uid, player)
    if not cfg.enabled or not uid then return end
    if not gate(uid) then return end -- cooldown / dedup
    logp(("HANDLING invite from %s uid=%s"):format(playerName(player), tostring(uid)))
    runner:handle({ uid = uid, player = player, name = playerName(player) })
  end

  -- Cache status; accept invites from incomingInvites (entry = {inviter,target,timestamp}).
  local function processStatus(s)
    if type(s) ~= "table" then return end
    latestStatus = s
    if not dumpedStatus then
      dumpedStatus = true
      logDump("status (trimmed)", { activeTrade = s.activeTrade, incomingInvites = s.incomingInvites, outgoingInvites = s.outgoingInvites })
    end
    if type(s.activeTrade) == "table" and not dumpedAT then dumpedAT = true; logDump("activeTrade fields", s.activeTrade) end
    local inv = s.incomingInvites
    if type(inv) == "table" then
      for uid, entry in pairs(inv) do
        if not dumpedInvite then dumpedInvite = true; logDump("incomingInvites entry", (type(entry) == "table" and entry) or { value = entry }) end
        local player = (type(entry) == "table" and (entry.inviter or entry.player)) or nil
        tryHandleInvite(uid, player)
      end
    end
  end

  local function connectStatus(name)
    local r = remotes[name]
    if r and r.OnClientEvent then
      r.OnClientEvent:Connect(function(a) processStatus(gamedata.unwrapStatus(a)) end)
      logok("listening on " .. name)
    end
  end
  connectStatus("trading_statuschange"); connectStatus("trading_tradebegan")

  -- Event path: inviter arrives as a Player. Funnel through the same gate.
  local dumpedInviteEvt = false
  if remotes.trading_invitesent then
    remotes.trading_invitesent.OnClientEvent:Connect(function(...)
      local args = { ... }
      if not dumpedInviteEvt then dumpedInviteEvt = true; logDump("trading_invitesent args", args) end
      local a = args[1]
      local inviter = (type(a) == "table" and a[1]) or a
      local uid
      if type(inviter) == "userdata" then pcall(function() uid = inviter.UserId end)
      elseif type(inviter) == "table" then uid = inviter.uid or inviter.id or inviter.UserId
      else uid = inviter end
      tryHandleInvite(uid, inviter)
    end)
    logok("listening on trading_invitesent")
  else
    logwarn("trading_invitesent absent")
  end

  -- Poll getStatus as the reliable driver (matches the base's polling model).
  local ticks = 0
  survival.watchdog(cfg, "trade-loop", function()
    while true do
      ticks = ticks + 1
      local s = gamedata.getStatus(remotes)
      if s then processStatus(s) end
      if ticks % 15 == 1 then
        local invCount = 0
        if latestStatus and type(latestStatus.incomingInvites) == "table" then
          for _ in pairs(latestStatus.incomingInvites) do invCount = invCount + 1 end
        end
        logp(("heartbeat: enabled=%s activeTrade=%s invites=%s gems=%s"):format(
          tostring(cfg.enabled), tostring(getActiveTrade() ~= nil), tostring(invCount), tostring(getGems())))
      end
      task.wait(1)
    end
  end, onEvent)

  advertiser.start({ cfg = cfg, feed = feed, ownedFn = inventory.owned, log = logp })
  setStatus("Ready. Trading " .. (cfg.enabled and "ENABLED" or "disabled") .. ". items=" .. libFeed.count(feed))
  logok("trading wired")
elseif not wrongPlace then
  setStatus("Not fully wired (remotes=" .. tostring(remotes ~= nil) .. " root=" .. tostring(rroot ~= nil) .. ").")
end

if (cfg.feedRefreshSec or 0) > 0 then
  task.spawn(function()
    while true do
      task.wait(cfg.feedRefreshSec)
      local fresh = fetchFeed()
      if fresh then for k in pairs(feed) do feed[k] = nil end; for k, v in pairs(fresh) do feed[k] = v end; logp("feed refreshed") end
    end
  end)
end

logstep("ready. items=" .. libFeed.count(feed) .. " remotes=" .. tostring(remotes ~= nil) .. " root=" .. tostring(rroot ~= nil))
logp("Send someone a trade / get an invite, then Copy Debug Report so I can confirm the shapes.")
