-- Bundled Universal Auto-Trade. Generated by tools/bundle.py. Do not edit.
-- Source of truth: src/*.lua  (regenerate: python tools/bundle.py)
local __M = {}
__M["lib.parse"] = (function()
local M = {}

-- Returns the first gem amount found in `s` as an integer, or nil.
-- Understands k/m suffixes (case-insensitive) and comma grouping.
function M.gems(s)
  if type(s) ~= "string" then return nil end
  s = s:lower()
  -- number with optional k/m suffix: e.g. 1.1m, 900k, 7k
  local num, suffix = s:match("([%d][%d,%.]*)%s*([km])")
  if num then
    local n = tonumber((num:gsub(",", "")))
    if not n then return nil end
    if suffix == "k" then n = n * 1000 elseif suffix == "m" then n = n * 1000000 end
    return math.floor(n + 0.5)
  end
  -- plain number, possibly comma-grouped
  local plain = s:match("[%d][%d,]*%.?%d*")
  if plain then
    local n = tonumber((plain:gsub(",", "")))
    if n then return math.floor(n + 0.5) end
  end
  return nil
end

return M

end)()
__M["lib.feed"] = (function()
local M = {}

-- Normalize a raw feed table { [name] = {value=?, demand=?} }.
-- Drops entries that aren't tables. Marks nil-value entries as naValue=true.
function M.normalize(raw)
  local out = {}
  if type(raw) ~= "table" then return out end
  for name, entry in pairs(raw) do
    if type(name) == "string" and type(entry) == "table" then
      local value = tonumber(entry.value)
      out[name] = {
        value = value,                 -- may be nil
        demand = tonumber(entry.demand) or 0,
        naValue = value == nil,
      }
    end
  end
  return out
end

function M.count(norm)
  local n = 0
  for _ in pairs(norm) do n = n + 1 end
  return n
end

return M

end)()
__M["lib.config"] = (function()
local M = {}

function M.defaults()
  return {
    enabled = false,
    globalMarkupPct = 5,      -- ask = value * (1 + markup/100)
    bandPct = 10,             -- ceiling/floor = value * (1 +/- band/100)
    demandScaling = true,     -- high demand -> more markup, less concession
    tradeUnitMode = "single_type_qty", -- single_copy | single_type_qty | multi_basket
    tradeTimeoutSec = 60,
    negotiation = { maxRounds = 4, concedeStepPct = 3, chatCooldownSec = 4 },
    ads = { rotatingAds = false, autoInvite = false, stockOnly = true, intervalSec = 45 },
    items = {},               -- [name] = { value?, markupPct?, bandPct?, forSale? }
  }
end

-- Deep-merge override onto base (base is not mutated). Tables recurse; scalars replace.
function M.merge(base, override)
  local out = {}
  for k, v in pairs(base) do
    if type(v) == "table" then out[k] = M.merge(v, {}) else out[k] = v end
  end
  if type(override) == "table" then
    for k, v in pairs(override) do
      if type(v) == "table" and type(out[k]) == "table" then
        out[k] = M.merge(out[k], v)
      else
        out[k] = v
      end
    end
  end
  return out
end

return M

end)()
__M["lib.pricing"] = (function()
local M = {}

local function round(n) return math.floor(n + 0.5) end

-- Returns { ask, ceiling, floor } for `qty` copies, or nil if unsellable.
-- feedEntry: { value?, demand?, naValue? }   override: { value?, markupPct?, bandPct? }
function M.quote(cfg, feedEntry, override, qty)
  override = override or {}
  qty = qty or 1
  local base = tonumber(override.value) or tonumber(feedEntry and feedEntry.value)
  if not base then return nil end  -- N/A and no override

  local markup = tonumber(override.markupPct) or cfg.globalMarkupPct or 0
  local band   = tonumber(override.bandPct)   or cfg.bandPct or 0
  local demand = tonumber(feedEntry and feedEntry.demand) or 0

  if cfg.demandScaling then
    -- demand 0..10 -> markup +0..+50% of itself; band shrinks up to -40%
    markup = markup * (1 + demand / 20)
    band   = band   * (1 - demand / 25)
  end

  local ask     = round(base * (1 + markup / 100)) * qty
  local ceiling = round(base * (1 + band / 100)) * qty
  local floor   = round(base * (1 - band / 100)) * qty
  return { ask = ask, ceiling = ceiling, floor = floor }
end

return M

end)()
__M["lib.negotiation"] = (function()
local M = {}

-- Current accept-threshold for a given round: starts at ceiling, steps down
-- toward floor by concedeStepPct of (ceiling-floor) per round, clamped at floor.
function M.threshold(cfg, quote, round)
  local step = (cfg.negotiation and cfg.negotiation.concedeStepPct or 0) / 100
  local span = quote.ceiling - quote.floor
  local t = quote.ceiling - span * step * (round or 0)
  if t < quote.floor then t = quote.floor end
  return math.floor(t + 0.5)
end

-- Decide the next move.
-- state: { offeredGems, targetChatNumber, round, elapsed }
-- Returns { action = "ACCEPT"|"COUNTER"|"HOLD"|"ABORT", amount?, message? }
function M.decide(cfg, quote, state)
  local maxRounds = cfg.negotiation and cfg.negotiation.maxRounds or 3
  local threshold = M.threshold(cfg, quote, state.round or 0)
  local offered = tonumber(state.offeredGems) or 0

  if offered >= threshold then
    return { action = "ACCEPT" }
  end

  local chat = tonumber(state.targetChatNumber)
  -- Out of rounds and still short -> give up.
  if (state.round or 0) >= maxRounds then
    return { action = "ABORT" }
  end

  if chat and chat >= quote.floor then
    -- counter toward the midpoint of their chat number and our threshold
    local counter = math.floor((chat + threshold) / 2 + 0.5)
    if counter < quote.floor then counter = quote.floor end
    if counter > quote.ceiling then counter = quote.ceiling end
    return { action = "COUNTER", amount = counter,
             message = ("I can do %d"):format(counter) }
  end

  if chat and chat < quote.floor then
    return { action = "ABORT" }
  end

  -- No usable signal yet: hold and wait for them to move.
  return { action = "HOLD" }
end

return M

end)()
__M["lib.ads"] = (function()
local M = {}

-- Short human form of a gem amount: 945000 -> "945k", 3675000 -> "3.7m",
-- 1000000 -> "1m", 810 -> "810". Always returns a single string.
function M.short(n)
  if n >= 1000000 then
    local s = ("%.1fm"):format(n / 1000000)
    s = (s:gsub("%.0m", "m"))
    return s
  elseif n >= 1000 then
    return ("%.0fk"):format(n / 1000)
  end
  return tostring(n)
end

-- Build a single advertisement line from listings { {name, ask}, ... }.
-- Returns nil when there is nothing to advertise.
function M.line(listings, opts)
  opts = opts or {}
  local maxItems = opts.maxItems or 5
  if #listings == 0 then return nil end
  local shown = math.min(maxItems, #listings)
  local parts = {}
  for i = 1, shown do
    parts[#parts + 1] = ("%s %s"):format(listings[i].name, M.short(listings[i].ask))
  end
  local msg = "Selling: " .. table.concat(parts, ", ")
  local omitted = #listings - shown
  if omitted > 0 then msg = msg .. (" +%d more"):format(omitted) end
  return msg .. " — msg me"
end

return M

end)()
__M["runtime.persist"] = (function()
-- Executor file persistence. All calls guarded: features degrade, never crash.
local HttpService = game:GetService("HttpService")
local M = {}
local FOLDER = "OdResto"
local SETTINGS = FOLDER .. "/autotrade_settings.json"
local FEEDCACHE = FOLDER .. "/value_cache.json"

local function ensureFolder()
  if makefolder and (isfolder == nil or not isfolder(FOLDER)) then
    pcall(makefolder, FOLDER)
  end
end

local function readJson(path)
  if not (isfile and isfile(path) and readfile) then return nil end
  local ok, raw = pcall(readfile, path)
  if not ok then return nil end
  local ok2, tbl = pcall(function() return HttpService:JSONDecode(raw) end)
  return ok2 and tbl or nil
end

local function writeJson(path, tbl)
  if not writefile then return false end
  ensureFolder()
  local ok, raw = pcall(function() return HttpService:JSONEncode(tbl) end)
  if not ok then return false end
  return (pcall(writefile, path, raw))
end

function M.loadSettings() return readJson(SETTINGS) end
function M.saveSettings(tbl) return writeJson(SETTINGS, tbl) end
function M.loadFeedCache() return readJson(FEEDCACHE) end
function M.saveFeedCache(tbl) return writeJson(FEEDCACHE, tbl) end

return M

end)()
__M["runtime.remotes"] = (function()
local Players = game:GetService("Players")
local M = {}

-- Resolve __THINGS.__REMOTES for the local player. Waits with a timeout.
-- Paths confirmed from the deobfuscation of plaza.lua.
function M.resolveRemotes(timeout)
  timeout = timeout or 30
  local lp = Players.LocalPlayer
  local things = lp:WaitForChild("__THINGS", timeout)
  if not things then return nil, "no __THINGS" end
  local remotes = things:WaitForChild("__REMOTES", timeout)
  if not remotes then return nil, "no __REMOTES" end
  local names = { "trading_acceptinvite", "trading_additem", "trading_removeitem",
                  "trading_confirmtrade", "trading_abort", "trading_sendmessage" }
  local out = {}
  for _, n in ipairs(names) do
    local r = remotes:WaitForChild(n, timeout)
    if not r then return nil, "missing remote " .. n end
    out[n] = r
  end
  return out
end

-- Load the untouched obfuscated base and return whatever it returns (if anything).
function M.loadBase(baseUrl)
  local ok, res = pcall(function()
    return loadstring(game:HttpGet(baseUrl))()
  end)
  return ok, res
end

-- Best-effort: force the base's own SmartTrade OFF via its saved-settings file,
-- so only our layer trades. The base reads OdResto/Trade-<name>.json on load.
-- Called BEFORE loading the base (see main.lua ordering).
function M.disableBaseSmartTradeFile()
  local ok = pcall(function()
    local HttpService = game:GetService("HttpService")
    local name = Players.LocalPlayer.Name
    local path = "OdResto/Trade-" .. name .. ".json"
    if isfile and isfile(path) and readfile and writefile then
      local t = HttpService:JSONDecode(readfile(path))
      t.smartTrade = false
      writefile(path, HttpService:JSONEncode(t))
    end
  end)
  return ok
end

return M

end)()
__M["runtime.inventory"] = (function()
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local M = {}

-- Returns { [SetName] = qty } for tradeable items the player owns.
-- Uses the game's Framework.Library, mirroring how the base reads inventory.
-- CONFIRM IN-GAME: the exact Library accessor + entry shape (see Task 10 checklist).
function M.owned()
  local out = {}
  local ok = pcall(function()
    local fw = ReplicatedStorage:WaitForChild("Framework", 10)
    local Library = require(fw):Library()          -- shape confirmed in-game
    local inv = Library.Inventory or (Library.GetInventory and Library:GetInventory())
    if type(inv) ~= "table" then return end
    for _, entry in pairs(inv) do
      if type(entry) == "table" then
        local name = entry.class or entry.Name
        if name then
          out[name] = (out[name] or 0) + (entry.count or entry.targetQty or 1)
        end
      end
    end
  end)
  if not ok then return {} end
  return out
end

return M

end)()
__M["runtime.trade"] = (function()
local pricing = __M["lib.pricing"]
local negotiation = __M["lib.negotiation"]

local M = {}

-- deps: { remotes, cfg, feed, chat, getTradeState, log }
--   remotes: table from remotes.resolveRemotes()
--   cfg: merged config; feed: normalized feed table
--   chat: { send=fn(text), lastNumberFrom=fn(playerName)->number|nil }
--   getTradeState: fn() -> { offeredGemsTarget, offeredItemsTarget, targetName,
--                            targetQty, wantedSet } | nil
--   log: fn(text)
function M.new(deps) return setmetatable({ d = deps, busy = false }, { __index = M }) end

function M:handleInvite()
  if self.busy then return end
  self.busy = true
  local d = self.d
  local ok, err = pcall(function()
    d.remotes.trading_acceptinvite:FireServer()
    local st = self:waitForOffer(d.cfg.tradeTimeoutSec)
    if not st or not st.wantedSet then return self:abort("no wanted set") end

    local feedEntry = d.feed[st.wantedSet]
    local override = (d.cfg.items or {})[st.wantedSet] or {}
    if override.forSale == false then return self:abort("not for sale: " .. st.wantedSet) end

    local qty = st.targetQty or 1
    local quote = pricing.quote(d.cfg, feedEntry or {}, override, qty)
    if not quote then return self:abort("unpriceable: " .. st.wantedSet) end

    self:addItem(st.wantedSet, qty)
    self:negotiate(st, quote)
  end)
  if not ok then self:abort("error: " .. tostring(err)) end
  self.busy = false
end

function M:negotiate(st, quote)
  local d = self.d
  local start = os.time()
  for round = 0, (d.cfg.negotiation.maxRounds or 3) do
    local cur = d.getTradeState() or st
    local decision = negotiation.decide(d.cfg, quote, {
      offeredGems = cur.offeredGemsTarget,
      targetChatNumber = d.chat.lastNumberFrom(st.targetName),
      round = round,
      elapsed = os.time() - start,
    })
    if decision.action == "ACCEPT" then
      d.remotes.trading_confirmtrade:FireServer()
      d.log(("Confirmed %s x%d for %s")
        :format(st.wantedSet, st.targetQty or 1, tostring(cur.offeredGemsTarget)))
      return
    elseif decision.action == "COUNTER" then
      d.chat.send(decision.message)
      task.wait(d.cfg.negotiation.chatCooldownSec or 4)
    elseif decision.action == "ABORT" then
      return self:abort("negotiation failed")
    else -- HOLD
      task.wait(2)
    end
    if os.time() - start > (d.cfg.tradeTimeoutSec or 60) then
      return self:abort("timeout")
    end
  end
  self:abort("max rounds")
end

function M:addItem(setName, qty)
  -- CONFIRM IN-GAME (Task 9): exact FireServer arg order for trading_additem.
  -- Best guess from deob: (setName/class, qty).
  self.d.remotes.trading_additem:FireServer(setName, qty)
end

function M:waitForOffer(timeout)
  local start = os.time()
  repeat
    local st = self.d.getTradeState()
    if st and st.offeredItemsTarget ~= nil then return st end
    task.wait(0.5)
  until os.time() - start > (timeout or 60)
  return self.d.getTradeState()
end

function M:abort(reason)
  pcall(function() self.d.remotes.trading_abort:FireServer() end)
  self.d.log("Aborted: " .. reason)
end

return M

end)()
__M["runtime.advertiser"] = (function()
local Players = game:GetService("Players")
local TextChatService = game:GetService("TextChatService")
local ads = __M["lib.ads"]
local pricing = __M["lib.pricing"]
local M = {}

local function sendChat(text)
  local ok = pcall(function()
    local ch = TextChatService:WaitForChild("TextChannels", 5)
                              :WaitForChild("RBXGeneral", 5)
    ch:SendAsync(text)
  end)
  return ok
end
M.sendChat = sendChat

-- Build the current sellable listings from config + feed (+ optional stock filter).
local function buildListings(cfg, feed, owned)
  local listings = {}
  for name, override in pairs(cfg.items or {}) do
    if override.forSale then
      if (not owned) or (owned[name] and owned[name] > 0) then
        local q = pricing.quote(cfg, feed[name] or {}, override, 1)
        if q then listings[#listings + 1] = { name = name, ask = q.ask } end
      end
    end
  end
  return listings
end
M.buildListings = buildListings

-- deps: { cfg, feed, ownedFn, log }
function M.start(deps)
  local cfg = deps.cfg
  task.spawn(function()
    while cfg.enabled do
      if cfg.ads.rotatingAds then
        local owned = cfg.ads.stockOnly and deps.ownedFn() or nil
        local line = ads.line(buildListings(cfg, deps.feed, owned), { maxItems = 5 })
        if line then sendChat(line); deps.log("Ad: " .. line) end
      end
      if cfg.ads.autoInvite then
        pcall(function()
          for _, plr in ipairs(Players:GetPlayers()) do
            if plr ~= Players.LocalPlayer then
              -- CONFIRM IN-GAME: the game's trade-invite request path.
            end
          end
        end)
      end
      task.wait(math.max(20, cfg.ads.intervalSec or 45)) -- floor 20s anti-spam
    end
  end)
end

return M

end)()
__M["runtime.ui"] = (function()
local M = {}

-- deps: { window, cfg, feed, save, onToggleEnabled }
-- window: a WindUI Tab handle exposed by main (built from the base's WindUI global).
-- CONFIRM IN-GAME: exact WindUI element method names/signatures (Task 13 checklist).
function M.build(deps)
  local cfg, save = deps.cfg, deps.save
  local tab = deps.window
  if not tab then return false end
  deps.selected = nil

  tab:Toggle({ Title = "Enable Universal Auto-Trade", Value = cfg.enabled,
    Callback = function(v) cfg.enabled = v; save(cfg); deps.onToggleEnabled(v) end })

  tab:Slider({ Title = "Global Markup %", Value = { Min = 0, Max = 50, Default = cfg.globalMarkupPct },
    Callback = function(v) cfg.globalMarkupPct = v; save(cfg) end })
  tab:Slider({ Title = "Negotiation Band %", Value = { Min = 0, Max = 30, Default = cfg.bandPct },
    Callback = function(v) cfg.bandPct = v; save(cfg) end })
  tab:Toggle({ Title = "Demand Scaling", Value = cfg.demandScaling,
    Callback = function(v) cfg.demandScaling = v; save(cfg) end })

  tab:Dropdown({ Title = "Trade Unit Mode",
    Values = { "single_copy", "single_type_qty", "multi_basket" },
    Value = cfg.tradeUnitMode,
    Callback = function(v) cfg.tradeUnitMode = v; save(cfg) end })

  tab:Toggle({ Title = "Rotating Chat Ads", Value = cfg.ads.rotatingAds,
    Callback = function(v) cfg.ads.rotatingAds = v; save(cfg) end })
  tab:Toggle({ Title = "Auto-Invite Nearby", Value = cfg.ads.autoInvite,
    Callback = function(v) cfg.ads.autoInvite = v; save(cfg) end })
  tab:Toggle({ Title = "Ads: In-Stock Only", Value = cfg.ads.stockOnly,
    Callback = function(v) cfg.ads.stockOnly = v; save(cfg) end })

  -- Per-item for-sale + override: searchable list.
  local names = {}
  for name in pairs(deps.feed) do names[#names + 1] = name end
  table.sort(names)
  tab:Dropdown({ Title = "Select Item to Configure", Values = names, Value = names[1],
    Callback = function(sel) deps.selected = sel end })
  tab:Toggle({ Title = "Selected: For Sale", Value = false,
    Callback = function(v)
      local s = deps.selected; if not s then return end
      cfg.items[s] = cfg.items[s] or {}; cfg.items[s].forSale = v; save(cfg) end })
  tab:Input({ Title = "Selected: Price Override (blank = use value)",
    Callback = function(txt)
      local s = deps.selected; if not s then return end
      cfg.items[s] = cfg.items[s] or {}
      cfg.items[s].value = tonumber(txt); save(cfg) end })
  return true
end

return M

end)()
-- === main ===
-- Universal Auto-Trade entry point. Loaded as one bundled script.
local CONFIG = {
  baseUrl = "https://raw.githubusercontent.com/0xfray/Mr-script/refs/heads/main/MR/plaza.lua",
  feedUrl = "https://raw.githubusercontent.com/0xfray/Mr-script/refs/heads/main/MR/value.lua",
}

local libConfig  = __M["lib.config"]
local libFeed    = __M["lib.feed"]
local libParse   = __M["lib.parse"]
local remotesM   = __M["runtime.remotes"]
local persist    = __M["runtime.persist"]
local inventory  = __M["runtime.inventory"]
local TradeM     = __M["runtime.trade"]
local advertiser = __M["runtime.advertiser"]
local ui         = __M["runtime.ui"]

local function logp(t) print("[AutoTrade] " .. t) end

-- 1) settings (merge saved over defaults)
local cfg = libConfig.merge(libConfig.defaults(), persist.loadSettings() or {})

-- 2) feed (fetch -> normalize -> cache; fall back to cache)
local feed
do
  local ok, raw = pcall(function() return loadstring(game:HttpGet(CONFIG.feedUrl))() end)
  if ok and type(raw) == "table" then
    feed = libFeed.normalize(raw); persist.saveFeedCache(raw)
  else
    feed = libFeed.normalize(persist.loadFeedCache() or {})
    warn("[AutoTrade] feed fetch failed; using cache (" .. libFeed.count(feed) .. " items)")
  end
end

-- 3) make sure the base's own SmartTrade won't run, then load the base
remotesM.disableBaseSmartTradeFile()
local okBase = remotesM.loadBase(CONFIG.baseUrl)
if not okBase then warn("[AutoTrade] base failed to load") end

-- 4) resolve remotes
local remotes, rerr = remotesM.resolveRemotes(30)
if not remotes then warn("[AutoTrade] " .. tostring(rerr)); return end

-- 5) chat adapter (records last number each player typed; sends counters)
local chatState = {}
do
  local TextChatService = game:GetService("TextChatService")
  local ok = pcall(function()
    TextChatService:WaitForChild("TextChannels", 10):WaitForChild("RBXGeneral", 10)
    TextChatService.MessageReceived:Connect(function(msg)
      local who = msg.TextSource and msg.TextSource.Name
      local n = libParse.gems(msg.Text)
      if who and n then chatState[who] = n end
    end)
  end)
  if not ok then warn("[AutoTrade] chat hook failed") end
end
local chat = {
  send = function(text) advertiser.sendChat(text) end,
  lastNumberFrom = function(name) return chatState[name] end,
}

-- 6) trade-state accessor (maps the live game trade object).
-- CONFIRM IN-GAME (Task 9/11): locate the real trade-state source and set the
-- fields { offeredGemsTarget, offeredItemsTarget, targetName, targetQty,
-- wantedSet, pendingInvite }. Placeholder reads a global the in-game pass sets.
local function getTradeState()
  return _G.__OdRestoTradeState
end

-- 7) wire trade runner to invite events
local runner = TradeM.new({
  remotes = remotes, cfg = cfg, feed = feed, chat = chat,
  getTradeState = getTradeState, log = logp,
})
task.spawn(function()
  while true do
    if cfg.enabled then
      local st = getTradeState()
      if st and st.pendingInvite then runner:handleInvite() end
    end
    task.wait(1)
  end
end)

-- 8) advertiser
advertiser.start({ cfg = cfg, feed = feed, ownedFn = inventory.owned, log = logp })

-- 9) UI (attach to base window; CONFIRM IN-GAME: window/tab handle from base)
pcall(function()
  ui.build({ window = _G.__OdRestoWindow, cfg = cfg, feed = feed,
             save = persist.saveSettings, onToggleEnabled = function() end })
end)

logp("ready (" .. libFeed.count(feed) .. " items).")

